# Configuração para o MySQL Real do XAMPP
spring.datasource.url=jdbc:mysql://localhost:3306/lojacarrodb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
# Credenciais exigidas pelo seu professor
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:}

# Hibernate / JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Desativar cache do Thymeleaf para atualizar o HTML na hora
spring.thymeleaf.cache=false